"""changed user profile to user data

Revision ID: 2e0c03d1faf7
Revises: 0392a8e4f015
Create Date: 2025-02-19 09:44:57.277532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0c03d1faf7'
down_revision: Union[str, None] = '0392a8e4f015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
