"""removed default from verification token

Revision ID: 4957721c83dc
Revises: e1bbdc7a0f9e
Create Date: 2025-02-13 23:44:01.374922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4957721c83dc'
down_revision: Union[str, None] = 'e1bbdc7a0f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
