"""updated model, fix user-report bug

Revision ID: 5f8186a01e6d
Revises: 8250eef6e458
Create Date: 2025-02-12 17:38:15.092749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8186a01e6d'
down_revision: Union[str, None] = '8250eef6e458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
