"""added OTP Model

Revision ID: 70099aad3d36
Revises: 2e0c03d1faf7
Create Date: 2025-02-19 10:15:40.240924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70099aad3d36'
down_revision: Union[str, None] = '2e0c03d1faf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_s',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('OTP', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_s_OTP'), 'otp_s', ['OTP'], unique=False)
    op.create_index(op.f('ix_otp_s_id'), 'otp_s', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_s_id'), table_name='otp_s')
    op.drop_index(op.f('ix_otp_s_OTP'), table_name='otp_s')
    op.drop_table('otp_s')
    # ### end Alembic commands ###
