"""changed otp name for easy understanding

Revision ID: 73cbc1bb2063
Revises: bfcdab5f6418
Create Date: 2025-02-19 10:37:27.784661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cbc1bb2063'
down_revision: Union[str, None] = 'bfcdab5f6418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
