"""changed position to rank

Revision ID: 76baae60186e
Revises: db1f5bd1516d
Create Date: 2025-02-16 10:55:50.077547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76baae60186e'
down_revision: Union[str, None] = 'db1f5bd1516d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('rank', sa.Float(), nullable=False))
    op.drop_constraint('unique_product_image_position', 'product_images', type_='unique')
    op.drop_column('product_images', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('unique_product_image_position', 'product_images', ['product_id', 'position'])
    op.drop_column('product_images', 'rank')
    # ### end Alembic commands ###
