"""changed product relationship image from lazy=dynamic to lazy =selectin

Revision ID: 9b2244c389f4
Revises: 287482b8d3f5
Create Date: 2025-02-14 23:15:58.180094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2244c389f4'
down_revision: Union[str, None] = '287482b8d3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
