"""added constrain to cart to allow only 50 quantities a time

Revision ID: a108657531c1
Revises: 76baae60186e
Create Date: 2025-02-16 09:07:02.610187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a108657531c1'
down_revision: Union[str, None] = '76baae60186e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
