"""changed otp name for easy understanding

Revision ID: bfcdab5f6418
Revises: 0dc1de000e0c
Create Date: 2025-02-19 10:32:32.937087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcdab5f6418'
down_revision: Union[str, None] = '0dc1de000e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_s', sa.Column('otp', sa.Integer(), nullable=False))
    op.add_column('otp_s', sa.Column('phone', sa.String(), nullable=False))
    op.drop_index('ix_otp_s_OTP', table_name='otp_s')
    op.create_index(op.f('ix_otp_s_otp'), 'otp_s', ['otp'], unique=False)
    op.create_index(op.f('ix_otp_s_phone'), 'otp_s', ['phone'], unique=False)
    op.drop_column('otp_s', 'OTP')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_s', sa.Column('OTP', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_otp_s_phone'), table_name='otp_s')
    op.drop_index(op.f('ix_otp_s_otp'), table_name='otp_s')
    op.create_index('ix_otp_s_OTP', 'otp_s', ['OTP'], unique=False)
    op.drop_column('otp_s', 'phone')
    op.drop_column('otp_s', 'otp')
    # ### end Alembic commands ###
