"""updated verification token

Revision ID: e1bbdc7a0f9e
Revises: 7cb6d406efe5
Create Date: 2025-02-13 23:33:43.916900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bbdc7a0f9e'
down_revision: Union[str, None] = '7cb6d406efe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'verification_tokens', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_tokens', type_='foreignkey')
    op.drop_column('verification_tokens', 'user_id')
    # ### end Alembic commands ###
